openapi: 3.0.0
info:
  title: People
  description: "The People API is used to get information about the people in an organisation."
  version: 0.1.0

servers:
  - url: https://api.peoplestack.app

paths:
  /people:
    get:
      summary: Gets a list of the people in the organisation.
      responses:
        '200':
          description: A JSON array of people
