openapi: 3.0.0
info:
  title: Directory
  description: "The Directory API is used to get information an organisation and its members"
  version: 0.1.0

servers:
  - url: https://api.peoplestack.app

paths:
  /directory:
    get:
      summary: Gets a list of the users in the organisation.
      responses:
        '200':
          description: A JSON array of users
